"""empty message

Revision ID: 14caf389c8bb
Revises: f16becee43f5
Create Date: 2020-05-10 11:07:29.672427

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '14caf389c8bb'
down_revision = 'f16becee43f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_linked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_linked')
    # ### end Alembic commands ###
