"""empty message

Revision ID: 73b9890b6f3f
Revises: 7ecc8e2c89b5
Create Date: 2020-05-08 21:47:10.763574

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '73b9890b6f3f'
down_revision = '7ecc8e2c89b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'last_updated')
    # ### end Alembic commands ###
