"""empty message

Revision ID: e65c8770c6b4
Revises: 73b9890b6f3f
Create Date: 2020-05-09 16:59:12.134391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65c8770c6b4'
down_revision = '73b9890b6f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_confirm', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('volunteer_confirm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'volunteer_confirm')
    op.drop_column('orders', 'client_confirm')
    # ### end Alembic commands ###
